export const filterData = [
            {name: "Flat Tire", image: require("../assets/images/flat_tire.png"), id: "0"},
            {name: "Dead Battery", image: require("../assets/images/battery.png"), id: "1"},
            {name: "Out of Fuel", image: require("../assets/images/fuel.png"), id: "2"},
            {name: "Engine Failure", image: require("../assets/images/engine.png"), id: "3"},
            {name: "Locked Keys", image: require("../assets/images/keys.png"), id: "4"},
            {name: "Towing", image: require("../assets/images/towing.png"), id: "5"},
            {name: "Others", image: require("../assets/images/others.png"), id: "6"}
];

export const mechanicsData = [
    {
      id: "0",
      name: "AutoProFix",
      image: "https://cdn11.bigcommerce.com/s-48ae1/product_images/uploaded_images/mecanico-mesa-de-trabajo-1.jpg",
      rating: 4.5,
      reviews: 100,
      coordinates: { lat: -26.18888612, lng: 28.05342102 },
      discount: 10,
      arrivalTime: 15,
      collectTime: 5,
      serviceType: "Flat Tire, Dead Battery",
      serviceData: [
        {
          name: "Flat Tire",
          price: 50,
          image: "https://www.allianzassistance.in/blog/Lock-out-or-flat-tyre-How-to-get-emergency-car-service-within-your-reach/_jcr_content/root/stage/stageimage.img.jpeg/1630231056950/istock-1191515181.jpeg",
        },
        {
          name: "Dead Battery",
          price: 100,
          image: "https://www.aceintheholetowing.com/uploads/8/7/8/4/87845272/bigstock-using-jumper-cables-to-start-a-46896721_orig.jpg",
        },
        {
          name: "Flat Tire - Premium Service",
          price: 150,
          image: "https://roadmech24x7.com/addedimage/flattypre11.jpg",
        },
        {
          name: "Dead Battery - Premium Service",
          price: 200,
          image: "https://di-uploads-pod12.dealerinspire.com/byerschevy/uploads/2023/07/Servicing-Engine-01.jpg",
        },
      ],
      distance: 2.5,
      price: 50,
      location: "Dhaka, Bangladesh",
      contact: "01700000000",
    },
    {
      id: "1",
      name: "Gearhead Garage",
      image: "https://www.suu.edu/blog/images/2018-06-cedar-city-mechanic-auto-repair.jpg",
      rating: 4.3,
      reviews: 85,
      coordinates: { lat: -33.924870, lng: 18.424055 },
      discount: 15,
      arrivalTime: 20,
      collectTime: 10,
      serviceType: "Engine Diagnostics, Brake Repairs",
      serviceData: [
        {
          name: "Engine Diagnostics",
          price: 80,
          image: "https://example.com/engine-diagnostics-image.jpg",
        },
        {
          name: "Brake Repairs",
          price: 120,
          image: "https://example.com/brake-repairs-image.jpg",
        },
      ],
      distance: 4.2,
      price: 70,
      location: "Cape Town, South Africa",
      contact: "02111111111",
    },
    {
      id: "2",
      name: "Wrench Wizards",
      image: "https://hips.hearstapps.com/hmg-prod/images/wrenches-set-in-the-workshop-royalty-free-image-1625006357.jpg",
      rating: 4.7,
      reviews: 120,
      coordinates: { lat: 40.7128, lng: -74.0060 },
      discount: 12,
      arrivalTime: 18,
      collectTime: 8,
      serviceType: "Transmission Services, Electrical Repairs",
      serviceData: [
        {
          name: "Transmission Services",
          price: 150,
          image: "https://example.com/transmission-services-image.jpg",
        },
        {
          name: "Electrical Repairs",
          price: 90,
          image: "https://example.com/electrical-repairs-image.jpg",
        },
      ],
      distance: 3.0,
      price: 80,
      location: "New York, USA",
      contact: "2122222222",
    },
    {
      id: "3",
      name: "Piston Power",
      image: "https://upload.wikimedia.org/wikipedia/commons/6/6c/Woman_mechanic_working_on_engine.jpeg",
      rating: 4.4,
      reviews: 95,
      coordinates: { lat: 51.5074, lng: -0.1278 },
      discount: 10,
      arrivalTime: 22,
      collectTime: 12,
      serviceType: "Tire and Wheel Services, Exhaust System Repairs",
      serviceData: [
        {
          name: "Tire and Wheel Services",
          price: 70,
          image: "https://example.com/tire-wheel-services-image.jpg",
        },
        {
          name: "Exhaust System Repairs",
          price: 110,
          image: "https://example.com/exhaust-system-repairs-image.jpg",
        },
      ],
      distance: 2.8,
      price: 75,
      location: "London, UK",
      contact: "02033333333",
    },
];

export const popmechanicsData = [
    {
        id: "0",
        name: "Speedy Repairs",
        image: "https://gwrench.com/wp-content/uploads/2022/10/AutoShopNearMeVista.jpg",
        rating: 4.2,
        reviews: 75,
        coordinates: { lat: 34.0522, lng: -118.2437 },
        discount: 10,
        arrivalTime: 20,
        collectTime: 8,
        serviceType: "Oil Change, Brake Repairs",
        serviceData: [
          {
            name: "Oil Change",
            price: 40,
            image: "https://gwrench.com/wp-content/uploads/2022/10/AutoShopNearMeVista.jpg",
          },
          {
            name: "Brake Repairs",
            price: 120,
            image: "https://gwrench.com/wp-content/uploads/2022/10/AutoShopNearMeVista.jpg",
          },
        ],
        distance: 5.1,
        price: 60,
        location: "Los Angeles, USA",
        contact: "2133333333",
      },
      {
        id: "1",
        name: "FixIt Fast",
        image: "https://e0.pxfuel.com/wallpapers/12/279/desktop-wallpaper-car-repair-page-1-auto-repair.jpg",
        rating: 4.8,
        reviews: 110,
        coordinates: { lat: 45.4215, lng: -75.6919 },
        discount: 15,
        arrivalTime: 18,
        collectTime: 7,
        serviceType: "Engine Diagnostics, Transmission Services",
        serviceData: [
          {
            name: "Engine Diagnostics",
            price: 80,
            image: "https://example.com/engine-diagnostics-image.jpg",
          },
          {
            name: "Transmission Services",
            price: 150,
            image: "https://example.com/transmission-services-image.jpg",
          },
        ],
        distance: 3.7,
        price: 90,
        location: "Ottawa, Canada",
        contact: "6134444444",
      },
      {
        id: "2",
        name: "Grease Monkeys",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSF_PiRhzk1tJHQOzAXM3dCyAut1E1wOzYTRg&usqp=CAU",
        rating: 4.6,
        reviews: 95,
        coordinates: { lat: -33.8650, lng: 151.2094 },
        discount: 12,
        arrivalTime: 22,
        collectTime: 10,
        serviceType: "Tire Rotation, Exhaust System Repairs",
        serviceData: [
          {
            name: "Tire Rotation",
            price: 60,
            image: "https://example.com/tire-rotation-image.jpg",
          },
          {
            name: "Exhaust System Repairs",
            price: 110,
            image: "https://example.com/exhaust-system-repairs-image.jpg",
          },
        ],
        distance: 6.4,
        price: 70,
        location: "Sydney, Australia",
        contact: "02-77777777",
      },
      
];